/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wiloon.javax;

import java.time.*;

public class Datetimex {

    public static void main(String[] args) {
        LocalTime time = LocalTime.of(14, 10, 21);
        System.out.println(time);
        LocalDateTime dateTime = LocalDateTime.of(2020, 4, 3, 17, 23, 59);
        System.out.println(dateTime);

        ZonedDateTime zoneDateTime = ZonedDateTime.now(ZoneId.of("America/New_York"));
        System.out.println(zoneDateTime);

        zoneDateTime = ZonedDateTime.now(ZoneId.of("Asia/Shanghai"));
        System.out.println(zoneDateTime);

        zoneDateTime = ZonedDateTime.of(2020, 4, 3, 17, 30, 22, 123, ZoneId.systemDefault());
        System.out.println(zoneDateTime);

        Instant instant = Instant.now();
        System.out.println(instant);
    }
}
